### ISSUE TITLE
GLFW和GLEW配置

### ISSUE THREAD

**Issue by maxim1um** [AirGuanZ/Atrc#1]
在readme中没看到GLFW和GLEW在windows上的相关配置。需要将这两个配置在哪个目录下，麻烦请详细说明。

**Comment by AirGuanZ** [comment]
它们在哪个目录下都可以，但是要让cmake能够找到其位置。如果cmake报找不到库，可以在生成项目的时候通过参数CMAKE_LIBRARY_DIR手动指定库的位置。
大部分靠谱的包管理器应该都会整理库的cmake config ，如果实在不行，可以改CMakeLists来设置头文件和链接的库文件。

**Comment by maxim1um** [comment]
看到你的CMakeList.txt里面有使用vcpkg包管理，在安装glfw和glew后还是会出现问题。glfw的安装triplets是x64-windows，glew的triplets是x64-windows-static，并且整个工程还需要使用的zlib。建议可以在readme上注明建议windows系统使用vcpkg，并提示安装依赖包的时候，注意triplets的不同。
