### ISSUE TITLE
How to rotate HDR on Z axis?

### ISSUE THREAD

**Issue by odil24** [AirGuanZ/Atrc#13]
Hi. I add + button and select to add Rotate option. But when i change on value for example 90° for degree it is appeared not on z but on strange axis position.

**Comment by AirGuanZ** [comment]
Hi, environment light rotation is implemented by transforming the hdr texture coordinate (uv). Thus, `Rotate` doesn't means to rotate the hdr sphere, but to rotate the uv on texture coordinate plane.

To rotate the hdr sphere along z axis, use `Translate` and use non-zero x offset. BTW, remember to set `Wrap U` to `Repeat` to handle out-of-range uv.

**Comment by odil24** [comment]
It didnt changed anything:
https://i.ibb.co/9V2LV4T/1.jpg

**Comment by odil24** [comment]
can you post with screenshot on how to do this exactly?

**Comment by AirGuanZ** [comment]
![image](https://user-images.githubusercontent.com/19588296/93295791-71cb1d00-f820-11ea-8c95-2a1c9d4c3fd8.png)
set translate offset to `0.5 0` means translateingthe environment texture coordinate with `0.5, 0`, which results in rotating the hdr sphere 180 degrees along z axis

**Comment by odil24** [comment]
:) works now. But can you change that value to range from 0-360 like real degree value for more artist control?
