### ISSUE TITLE
Is it possible to use UV from imported OBJ file?

### ISSUE THREAD

**Issue by odil24** [AirGuanZ/Atrc#15]
I UV mapped and textured inside Blender one scene and exported it to OBJ file. After that i imported inside AtrC and apply texture to the objects BUT in rendering it cant applied UVs as in Blender. So how to use UVs from extracted OBJ file?

**Comment by AirGuanZ** [comment]
Atrc will use texture coordinate in obj. but it may address the texture differently from blender —— try to use 'Repeat' wrap mode and 'Inv V' to match the behavior of blender.

**Comment by odil24** [comment]
I will try. Thanks.
