### ISSUE TITLE
Are you planned GPU rendering for the engine?

### ISSUE THREAD

**Issue by odil24** [AirGuanZ/Atrc#18]
I think a lot of users are would like if it will be have GPU Compute for faster rendering. So, will it be integrate in near future?

**Comment by AirGuanZ** [comment]
I am planning to rewrite the renderer into a wavefront CPU/GPU path tracer. However, I'm busy with finishing my thesis and finding a job this year. So I cannot promise when the rewriting will begin.

**Comment by odil24** [comment]
Thanks for answer.
BTW: Check your mail account about the job I sent.
