### ISSUE TITLE
按照文档编译项目出现错误，可以帮忙看一下吗？报错信息如下

### ISSUE THREAD

**Issue by Chris-Zou** [AirGuanZ/Atrc#2]
Determining if the include file pthread.h exists failed with the following output:
Change Dir: E:/Atrc/build/CMakeFiles/CMakeTmp

Run Build Command:"C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/MSBuild/15.0/Bin/MSBuild.exe" "cmTC_ff113.vcxproj" "/p:Configuration=Debug" "/p:Platform=x64" "/p:VisualStudioVersion=15.0"
Microsoft (R) Build Engine version 15.9.21+g9802d43bc3 for .NET Framework

Copyright (C) Microsoft Corporation. All rights reserved.

Build started 2019-09-23 16:34:22.

Project "E:\Atrc\build\CMakeFiles\CMakeTmp\cmTC_ff113.vcxproj" on node 1 (default targets).

PrepareForBuild:

  Creating directory "cmTC_ff113.dir\Debug\".

  Creating directory "E:\Atrc\build\CMakeFiles\CMakeTmp\Debug\".

  Creating directory "cmTC_ff113.dir\Debug\cmTC_ff113.tlog\".

InitializeBuildStatus:

  Creating "cmTC_ff113.dir\Debug\cmTC_ff113.tlog\unsuccessfulbuild" because "AlwaysCreate" was specified.

ClCompile:

  C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\bin\HostX86\x64\CL.exe /c /Zi /W3 /WX- /diagnostics:classic /Od /Ob0 /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\"Debug\"" /D _MBCS /Gm- /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"cmTC_ff113.dir\Debug\\" /Fd"cmTC_ff113.dir\Debug\vc141.pdb" /Gd /TC /errorReport:queue E:\Atrc\build\CMakeFiles\CMakeTmp\CheckIncludeFile.c

  Microsoft (R) C/C++ Optimizing Compiler Version 19.16.27027.1 for x64
  Copyright (C) Microsoft Corporation.  All rights reserved.

  cl /c /Zi /W3 /WX- /diagnostics:classic /Od /Ob0 /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\"Debug\"" /D _MBCS /Gm- /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"cmTC_ff113.dir\Debug\\" /Fd"cmTC_ff113.dir\Debug\vc141.pdb" /Gd /TC /errorReport:queue E:\Atrc\build\CMakeFiles\CMakeTmp\CheckIncludeFile.c
  CheckIncludeFile.c

E:\Atrc\build\CMakeFiles\CMakeTmp\CheckIncludeFile.c(1): fatal error C1083: Cannot open include file: 'pthread.h': No such file or directory [E:\Atrc\build\CMakeFiles\CMakeTmp\cmTC_ff113.vcxproj]
Done Building Project "E:\Atrc\build\CMakeFiles\CMakeTmp\cmTC_ff113.vcxproj" (default targets) -- FAILED.

Build FAILED.

"E:\Atrc\build\CMakeFiles\CMakeTmp\cmTC_ff113.vcxproj" (default target) (1) ->

(ClCompile target) -> 

  E:\Atrc\build\CMakeFiles\CMakeTmp\CheckIncludeFile.c(1): fatal error C1083: Cannot open include file: 'pthread.h': No such file or directory [E:\Atrc\build\CMakeFiles\CMakeTmp\cmTC_ff113.vcxproj]

    0 Warning(s)
    1 Error(s)
Time Elapsed 00:00:00.47

**Comment by AirGuanZ** [comment]
这是cmake用于查探环境中是否有pthread.h所使用的测试代码，在我这里正常构建的过程中也会出现，输出信息和你的基本一致。因此如果总的构建过程失败了，应该还会输出其他错误信息，能否发出来看一下

**Comment by Chris-Zou** [comment]
由于评论不能附加附件，所以日志文件用邮箱发给你了。
