### ISSUE TITLE
Any news from NOT-PUBLIC repo on AtrCRenderer?

### ISSUE THREAD

**Issue by odil24** [AirGuanZ/Atrc#21]
AS you said on closed issue topic you've been mentioned that you've started working on non-public branch of AtrC? so?

**Comment by AirGuanZ** [comment]
I have finished some preparation like [cuj](https://github.com/AirGuanZ/cuj), which will be used for material graph compilation. However, a whole new CPU/GPU renderer needs a lot of work and I'm busy with my master dissertation. So no recent milestone/roadmap can be guaranteed.
