### ISSUE TITLE
关于三角形SurfacePoint的user和geometry coord的计算问题

### ISSUE THREAD

**Issue by wyzwzz** [AirGuanZ/Atrc#24]
```c++
  const FVec3 user_z = prim_info.n_a_ + rcd.uv.x * FVec3(prim_info.n_b_a_)
                                     + rcd.uv.y * FVec3(prim_info.n_c_a_);
  inct->user_coord = inct->geometry_coord.rotate_to_new_z(user_z);
```
在```triangle_bvh.cpp```里的这两行计算shading的局部坐标系时 计算dndu和dndv时 为什么不采用和计算dpdu和dpdv一样的公式
而是直接旋转三角形的面法向量得到呢？另外我有点疑惑将一个坐标系的z轴旋转到新的z轴后 原来的x和y轴的变换是有公式的嘛还是任意计算的呢？我原来以为旋转轴是固定的 是绕着new_z和old_z叉乘得到的那个轴旋转 但是我看大佬代码好像不是这样 不是很理解...
希望大佬能解释一下 感谢不尽T..T
```c++
inline _simd_coord_float3_t::self_t _simd_coord_float3_t::rotate_to_new_z(
    const axis_t &new_z) const noexcept
{
    axis_t new_x = cross(y, new_z);
    axis_t new_y = cross(new_z, new_x);
    return self_t(new_x, new_y, new_z);
}
```

**Comment by AirGuanZ** [comment]
构造geometry frame时，理论上应该优先使用用户输入的tangent frame，我处理输入没考虑这个，就顺手用了dpdu来构造。

构造shading frame时理论上也可以借助uv来计算，不过这不是个well defined的问题，旋转geometry frame的效果还不错，我就一直沿用了。旋转时叉乘的做法也是随手写的，这里应该没有标准答案，着色结果看着对就行。比如，一个更加符合直觉的做法是构造从geometry normal旋转到shading normal的四元数，然后用它去旋转整个frame。
