### ISSUE TITLE
关于pt直接光的多重重要性采样问题

### ISSUE THREAD

**Issue by wyzwzz** [AirGuanZ/Atrc#25]
在```pace_tracing.cpp```里面对直接光的采样 会对所有光源先采样再对```bsdf```采样
```c++
            //采样光源
            for(auto light : scene.lights())
            {
                direct_illum += coef * mis_sample_light(
                    scene, light, ent_inct, ent_shd, sampler);
            }
            //采样bsdf
            direct_illum += coef * mis_sample_bsdf(
                scene, ent_inct, ent_shd, sampler);
```
有两个问题想请教一下：
 1.对所有光源采样结果是收敛更快，但是如果场景的```diffuse light```特别多的话，好像特别费时间，特别是那种用三角网格代表的球形```area light```，每一个单独的三角形都是一个光源，会不会造成时间消耗加大很多？
  2.为什么要把对光源的采样和```bsdf```的采样分开呢？我在PBRT里看到的做法是：对一个光源采样时包括了对光源和```bsdf```的采样。类似于代码如下，我是不是没理解明白什么...
```c++
            for(auto light : scene.lights())
            {
                //采样光源
                direct_illum += coef * mis_sample_light(
                    scene, light, ent_inct, ent_shd, sampler);
                //采样bsdf
                direct_illum += coef * mis_sample_bsdf(
                        scene, ent_inct, ent_shd, sampler);
            }
```
还有个对我来说比较费解的问题，为什么使用```path tracing```会出现离```diffuse light```很近的地方太亮，有种过曝光的感觉，离光源很远的地方不够亮，是这种渲染方法的限制嘛？
我看大佬的```ibl```里面好像不需要做对采样时传进来的方向做转换，但是```environment light```的坐标系和相机的坐标系是不一样的来着，前者是局部坐标系以z轴为上，而后者以y轴为上，莫非其他地方处理过了orz...
感谢大佬的解答！

**Comment by AirGuanZ** [comment]
1. 是的，这是个很暴力的做法，对大量光源很吃瘪。当然，你说的每个三角形当光源在这里倒也不会出现，我做了个mesh light，可以把一整个triangle mesh当成一个光源。更practical的做法是用一定的自适应策略选择少量光源进行着色，如light bvh等many light方案。
2. 只要pdf计算得当两种方法都是无偏的。我把bsdf sampling分离出来的原因是我认为bsdf采样会击中的light和循环中指定的light一般来说没啥关系。事实上这两种策略都不怎么样，一个更加合理的方案是把bsdf sampling和next bounce的求交合并起来，可以省一次求交计算。
3. 离光源近的位置更亮很符合直觉嘛😂我认为这很难说是“限制”，而是真实世界就是如此。如果你想避免画面出现过曝、暗部细节丢失等问题，一是在设计场景时进行合理的打光，二是使用诸如local tone mapping、auto exposure等技术对渲染出的画面进行调整。
4. 摄像机射出去的射线是world space里的，另外我记得atrc的camera是可以调整up向量从而调整在世界空间中的“上方”的。

BTW，Atrc是学习性的渲染器，里面很多东西都是原理说得过去但性能不怎么样的。我最近在做一个更加practical的渲染器[Btrc](https://github.com/AirGuanZ/Btrc)，更更加重视它的效率和扩展能力。

**Comment by wyzwzz** [comment]
请问一般场景构建会采用什么格式的数据呢？我看editor里面支持导入obj格式的模型，但是似乎不会同时导入.mtl文件的配置。然后我在doc里也没找到如何在editor里面指定材质的教程... 那么对于obj导入的模型来说，可能有多个mesh对应多个材质，这应该怎么指定呢？好奇大佬的这些图片都是用什么格式的场景数据渲染的，我看很多场景资源找到时的格式都是blend

**Comment by wyzwzz** [comment]
顺便我觉得phong材质的镜面好像很容易出现白噪点，那种很难通过收敛去除的白噪点...

**Comment by AirGuanZ** [comment]
我一般是导入白模后自己去设置材质和调整灯光。理论上也可以弄个读mtl，不过可能我觉得设置场景也有一些乐趣吧。

**Comment by AirGuanZ** [comment]
> 顺便我觉得phong材质的镜面好像很容易出现白噪点，那种很难通过收敛去除的白噪点...

可能是材质本身的采样策略不佳，或者glossy部分在场景中形成了难以采样的复杂光路，需要更适合的算法
