### ISSUE TITLE
Can you upload latest build for win64?

### ISSUE THREAD

**Issue by odil24** [AirGuanZ/Atrc#3]
Hi. I'm interested on latest build which is updated latest commits. I need for Win10 x64.
Thanks.

**Comment by AirGuanZ** [comment]
Sure. The [Release](https://github.com/AirGuanZ/Atrc/releases/tag/v0.1.1) page has been updated.
However this project is under heavy refactoring on a non-public dev branch. So only some bug fixes will be committed.

**Comment by odil24** [comment]
Thank you for the reply. So is it merged with latest commits? For example, with 3days ago?
