### ISSUE TITLE
How to add Sun lamp to the scene?

### ISSUE THREAD

**Issue by odil24** [AirGuanZ/Atrc#4]
How and how to change Sun lamp settings?

**Comment by AirGuanZ** [comment]
right-side panel -> Global -> Environment, and change the environment light type from 'Native Sky' to 'IBL', then you can select a `.hdr` file.

**Comment by odil24** [comment]
@AirGuanZ but i need not HDR map i want to add real sun.

**Comment by AirGuanZ** [comment]
Sorry... This hasn't been supported. As you can see, this is a personal path tracing lab used in learning and research, so it lacks a lot of production features.

**Comment by odil24** [comment]
@AirGuanZ from personal to prod-ready will be in future

**Comment by odil24** [comment]
You've done a lot of hard works here already.
