### ISSUE TITLE
Is it supported alpha-masked textures for transparency?

### ISSUE THREAD

**Issue by odil24** [AirGuanZ/Atrc#7]
Is it possible to render this kind of texture in the editor? For example if i have a tree with leafs?

**Comment by AirGuanZ** [comment]
Sorry.. this is not supported for now. I will add it in next release

**Comment by odil24** [comment]
@AirGuanZ cant wait to see it.

**Comment by odil24** [comment]
> Sorry.. this is not supported for now. I will add it in next release

Is there have any news on alpha-masked textures?
