### ISSUE TITLE
How to change Camera manually?

### ISSUE THREAD

**Issue by odil24** [AirGuanZ/Atrc#8]
I goto Camera panel. Goto Edit Camera. It has floated values but how to change it? It can not support dot ( ● ) value like 0.1 or ( , ) value like 0,1 (when i change from 0.1 to 0,1 it gone black camera.

**Comment by AirGuanZ** [comment]
which value did you change? I can edit the camera in right panel or in the previewer normally.

**Comment by odil24** [comment]
> which value did you change? I can edit the camera in right panel or in the previewer normally.

Is it supported ( . ) or ( , )? I mean press on the value and increased/decreased from numbers.
